### ISSUE TITLE
Crashes when Ghast touches minecart.

### ISSUE THREAD

**Issue by void732** [stormdirus2/Memento-Mori#2]
A field called "noTouchyTouch" leads to the ClassCastException error.

I dink dis is from your recent updt that includes "body touch cause hostile mobs to notice your "Player-hood""...

**Comment by void732** [comment]
And first, dis's a great add-on. Dis doesn't change.
But according to dis updt(ver. 2.0.2), the llama will attack you even u'r a skeleton that collides with it... And etc....

**Comment by void732** [comment]
net.minecraft.class_1695 cannot be cast to net.minecraft.class_1309
(accordin' to yarn's tiny mappings, it should be "net/minecraft/entity/vehicle/MinecartEntity" can't interact with "net/minecraft/entity/LivingEntity".)

**Comment by void732** [comment]
Ultreia Et Suseia!!!

**Comment by stormdirus2** [comment]
Thankyousomuch!

Man, how did I not see this?

Musta been tired or something 0_0

Just made a commit fixing this glitch, will be building and adding binaries to curseforge shortly.
