### ISSUE TITLE
When possess to an undead mob, you use Soul Cleaving enchan. to self-tormenting...

### ISSUE THREAD

**Issue by void732** [stormdirus2/Memento-Mori#4]
Hey, me again.("void7327" in CurseForge) Thanks for fixing the "cast an Entity to LivingEntity" bug.

(Continuation of the title) to self-tormenting yourself, you don't take any soul damage...
For an instance, you use a Soul Cleaving III enchanted bow to damage yourself... But it's different when you are mortal or possessed... e.g. skeleton doesn't take any soul damage from Soul Cleaving enchantment, but mortal does. (self-damage)

From who love this MOD very...

![2021-05-01_23 32 33](https://user-images.githubusercontent.com/48733991/116785670-c54f5a00-aad5-11eb-890f-9ec3e16e4d3d.png)
(img. 1.  self-tormenting)

**Comment by void732** [comment]
Sorry, I missed something.
This happens only when I'm possessing a skeleton. Not zombie.

**Comment by void732** [comment]
One more thing. Can I donate you, or have a pull request in this Memento Mori?
(If this can be had pull request, plz teach how to build. Because I have been trying build by IntelliJ but failed because of "
```
processResources {
    finalizedBy runData
}
```
" makes  `NoClassDefFoundError`.

**Comment by stormdirus2** [comment]
This only happens when you are possessing a skeleton? Quite odd.
My only thought is that either this is a vanilla functionality problem, or a mod interaction.

On the odd case it happens to be my doing, it must be a vague bug or something I heavily overlooked.

As for building the project, I likely left out some of the files needed to build, I will attempt to fix this shortly.

**Comment by James103** [comment]
Actually, possessing a Zombie and shooting yourself with a Soul Cleaving bow has the same effect (increased Attrition) as doing the same as a Skeleton.

**Comment by stormdirus2** [comment]
@Void-heart 
> One more thing. Can I donate you, or have a pull request in this Memento Mori?
> (If this can be had pull request, plz teach how to build. Because I have been trying build by IntelliJ but failed because of "
> 
> ```
> processResources {
>     finalizedBy runData
> }
> ```
> 
> " makes `NoClassDefFoundError`.

Yo, I just pushed a new version, it should fix this problem. Let me know if you still have trouble building or experience some other related issue.

Thanks for all the help btw, makes deving this mod and identifying problems much easier. You and @James103 both. :+1:

**Comment by void732** [comment]
Seems like yr new updt fixes everything... (*≧︶≦))(￣▽￣* )ゞ

P.S.  Thank you very very much...

**Comment by void732** [comment]
But one thing...
https://github.com/stormdirus2/Memento-Mori/issues/6#issuecomment-830733672

P.S. /give command issue. Other things in that comment were all fixed.

**Comment by stormdirus2** [comment]
:thinking: 
I am not able to replicate this issue. Until tried-and-true procedure arises I am closing it.

**Comment by void732** [comment]
Not quite understand wat u'r meaning. But from your recent updt(ver. 2.1.0) this issue solved actually, but then you were still updating continuously... However, thanks very very much for being patient on this issue...

**Comment by void732** [comment]
I think it's my bad that I didn't close it in time...
