### ISSUE TITLE
Untranslated strings: `gamerule.mementomori:(gamerule_id)`

### ISSUE THREAD

**Issue by James103** [stormdirus2/Memento-Mori#5]
As of `mementomori-2.0.3+1.16.5-fabric`, the following strings relating to game rules are untranslated.

String ID | My English translation
--- | ---
gamerule.mementomori:attritionGrowth | Grow attrition while possessing
gamerule.mementomori:attritionGrowth.description | Controls whether or not attrition will increase as a mob
gamerule.mementomori:attritionTime | Attrition time (seconds)
gamerule.mementomori:attritionTime.description | Controls the amount of time, in seconds, that a player has attrition for
gamerule.mementomori:blastResistantUnphasable | Ghosts can't pass through obsidian
gamerule.mementomori:blastResistantUnphasable.description | Controls if players are not able to go through blocks with a blast resistance of 1200 or higher
gamerule.mementomori:cureAllItems | Enchanted golden apples cure without weakness
gamerule.mementomori:cureAllItems.description | Controls whether or not `cure_alls` items can cure a possessed without the weakness debuff

These strings can be found by going to the create a new world screen, clicking "Game Rules", and scrolling down a bit.

The `en_us` translations for the strings without `.description` are my original work, while the `en_us` translations for the strings with `.description` are taken from [the README](https://github.com/stormdirus2/Memento-Mori#gamerules).

**Comment by stormdirus2** [comment]
Ah yes, I have been meaning to get around to this for a while.

Might actually get it done today, however I have been working on new additions.

Thanks for putting them all in one spot, it makes this much, much easier!
