### ISSUE TITLE
Attrition IV can go (way, way) past 20 minutes.

### ISSUE THREAD

**Issue by James103** [stormdirus2/Memento-Mori#6]
As of mementomori-2.0.3+1.16.5-fabric, it is possible for Attrition IV to go way, way past 20 minutes. To reproduce this,

1. Create a new world with cheats enabled, Requiem 1.5.1 installed, and the aforementioned `mementomori` mod.
2. `/summon minecraft:zombie ~ ~ ~ {Fire:99999999,HandItems:[{id:"minecraft:bow",Count:1b,tag:{Enchantments:[{id:"mementomori:soul_cleaving",lvl:1600s}]}},{id:"minecraft:arrow",Count:10b}]}`
3. Let the zombie hit you.
4. You instantly die regardless of current HP as expected (as you reached Attrition IV and died due to excessive soul damage).
5. However, you now have Attrition IV for `**:**` (which actually lasts several hours) instead of the expected `20:00` (default value of `mementomori:attritionTime`).

I would expect for Attrition to be capped at the value of `mementomori:attritionTime` for each level, including level IV.

**Comment by void732** [comment]
And I can't use 
`/give Void7327(yr name) minecraft:diamond_sword{Enchantments:[{id:"soul_cleaving",lvl:1000}]}` command...
But I can use 
`/give Void7327(yr name) minecraft:diamond_sword{Enchantments:[{id:"sharpness",lvl:10000}]}` command...

And this's no effect when u'r holding an enchanted sword that like 1000lvl. Soul Cleaving and as undead like a zombie, to attack other mobs. They're not one-shot-killable... 
But when u'r holding Soul Cleaving 1000lvl. bow, you can one-shot other mobs by shooting them(not hitting with the bow itself).

p.s. But when you're a mortal and holding Soul Cleaving 1000lvl. enchanted sword, you can one-shot other mobs.

**Comment by void732** [comment]
Of course, your command
`/summon minecraft:zombie ~ ~ ~ {HandItems:[{id:"minecraft:wooden_sword",Count:1,tag:{Enchantments:[{id:"mementomori:soul_cleaving",lvl:1600}]}}]}`
is working. They're holding Soul Cleaving 1600lvl. enchanted thing.

p.s. And can one-shot you.

**Comment by void732** [comment]
_Attrition IV can go (way, way) past 20 minutes._
OK, this looks like a feature that stormdirus2 designed on purpose. 
Because of the source code of Memento Mori.
```
public static void IncrementSoul(LivingEntity Entity, int Increment) {
        int total = Math.max(getTotalTime(Entity) + Increment * 20, 0);
        int attritionTime = Entity.world.getGameRules().getInt(MementoMori.attritionTime) * 20;
        int totalTime = attritionTime * 3;
        if (total < totalTime) {
            setTotalTime(Entity, total);
        } else {
            setTotalTime(Entity, total);
            PlayerEntity player = Entity instanceof PlayerEntity ? (PlayerEntity) Entity : null;
            if (player == null || !RemnantComponent.get(player).isIncorporeal()) {
                Entity.damage(DamageSource.OUT_OF_WORLD, 100);
            }
        }
    }
```
You can see that even when our soul damage makes the Attrition Time went more than totalAttritionTime, it's made to store the Attrition Time data instead of "to be capped at the value of `mementomori:attritionTime`" as you said.

**Comment by stormdirus2** [comment]
Definitely deliberate.

**Comment by stormdirus2** [comment]
@Void-heart 
> And I can't use
> `/give Void7327(yr name) minecraft:diamond_sword{Enchantments:[{id:"soul_cleaving",lvl:1000}]}` command...
> But I can use
> `/give Void7327(yr name) minecraft:diamond_sword{Enchantments:[{id:"sharpness",lvl:10000}]}` command...
> 
> And this's no effect when u'r holding an enchanted sword that like 1000lvl. Soul Cleaving and as undead like a zombie, to attack other mobs. They're not one-shot-killable...
> But when u'r holding Soul Cleaving 1000lvl. bow, you can one-shot other mobs by shooting them(not hitting with the bow itself).
> 
> p.s. But when you're a mortal and holding Soul Cleaving 1000lvl. enchanted sword, you can one-shot other mobs.

Ah, tis a simple issue. You are using "soul_cleaving" rather than "mementomori:soul_cleaving" like they are.
