### ISSUE TITLE
Undocumented: Touching neutral mob while possessing acts as if you attacked that mob

### ISSUE THREAD

**Issue by James103** [stormdirus2/Memento-Mori#7]
Exactly as it says in the title. To reproduce:

1. Create a new world with cheats enabled and the aforementioned mods installed.
2. Possess any mob.
3. `/summon bee`
4. Notice that the summoned bee is automatically angry at you.
5. Go to the Nether.
6. Be within line of sight of some Zombified Piglins.
7. `/summon zombified_piglin`
8. Notice that all of the zombified piglins near you are angry at you (as if you attacked the mob that you `/summon`ed).

When fixing this, either the automatic anger should be limited to true hostile mobs only or the following line in [the README](https://github.com/stormdirus2/Memento-Mori#changes) should be changed:

Current:
> Therefore, hostile mobs will attack you even while possessing their brethren if you collide with em'.

Expected:
> Therefore, hostile **and neutral** mobs will attack you even while possessing their brethren if you collide with em'.

Mod list (MC 1.16.5):
```
requiem-1.5.1
mementomori-2.0.3+1.16.5-fabric
fabric-api-0.29.3+1.16
cloth-config-4.11.19-fabric
modmenu-1.14.13+build.19
```

**Comment by stormdirus2** [comment]
Interesting, although not entirely intentional, I believe I'll keep it.
I'll update the descriptions shortly.

Very helpful, as always. Thank you!
