### ISSUE TITLE
Death should inflict 1200 soul damage instead of directly incrementing Attrition level.

### ISSUE THREAD

**Issue by James103** [stormdirus2/Memento-Mori#9]
Currently, if you die while possessing a mob (or even while human), your Attrition level gets incremented directly and the duration resets to the value of `mementomori:attritionTime` in seconds. This has the effect of increasing your Attrition by 2 levels every time you die, because of the following:
1. You die and gain Attrition I for 20:00 [1st death].
2. You possess a mob.
3. Since you have Attrition >= 20 minutes, the excess overflows and you gain Attrition II for a single tick.
4. The mob you're possessing dies [2nd death].
5. Your 0.05 seconds of Attrition II becomes 20 minutes of Attrition III. Effectively, you took 2399.95 soul damage as a result of your possessed mob's death instead of the expected 1200.
6. You possess another mob.
7. Since you have Attrition >= 20 minutes, the excess overflows and you gain Attrition IV for a single tick.
8. Therefore, you reach Attrition IV after 2 deaths instead of the expected 4.

What should happen should be like the following:
1. You die and take 1200 soul damage, bringing you from no Attrition to Attrition I (20:00) [1st death].
2. You possess a mob.
3. Since you have Attrition >= 20 minutes, the excess overflows and you gain Attrition II for a single tick.
4. The mob you're possessing dies [2nd death].
5. Your 0.05 seconds of Attrition II should become 0.05 seconds of Attrition III. In other words, you should just take the 1200 soul damage instead of rounding up the Attrition to the next level at its max duration.
6. The mob you're possessing dies [3rd death].
7. Your 0.05 seconds of Attrition III should become 0.05 seconds of Attrition IV for similar reason as in step 5.
8. Therefore, you should reach Attrition IV after 3 deaths, not 2.

This still has the effect of giving you Attrition II on your first death and possession, but further deaths and possessions will only increase your Attrition by 1 level each time instead of 2 levels.

Another example: Suppose you have 10 minutes of Attrition II. Dying should result in you taking 1200 soul damage and bringing you to 10 minutes of Attrition III, but you currently get brought to 20 minutes of Attrition III, equivalent to you taking 1800 soul damage.

Note: the 1200 soul damage you take on death is equal to the value of the gamerule `mementomori:attritionTime`. That is, if `/gamerule mementomori:attritionTime` is 60 seconds instead of 1200, you will take 60 soul damage when you die, which will still increase your Attrition by exactly 1 level.

Modlist (MC 1.16.5):
```
Mods:
  [✔️] cloth-config-4.11.19-fabric
  [✔️] fabric-api-0.29.3+1.16
  [❌] mementomori-2.0.3+1.16.5-fabric.jar (disabled)
  [✔️] mementomori-2.2.0+1.16.5-fabric
  [✔️] modmenu-1.14.13+build.19
  [❌] requiem-1.4.4.jar (disabled)
  [❌] requiem-1.5.0.jar (disabled)
  [✔️] requiem-1.5.1
  [❌] requiem-pandemonium-1.4.4.jar (disabled)
  [❌] requiem-pandemonium-1.5.0.jar (disabled)
  [❌] requiem-pandemonium-1.5.1.jar (disabled)
```

**Comment by stormdirus2** [comment]
Right. I should reuse soul damage to increment duration rather than simply set it another amplitude higher and then resetting the duration.

**Comment by stormdirus2** [comment]
Fixed with latest release (will publish to CurseForge shortly).
